# Generated by Django 4.2.16 on 2026-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='QUEUED', max_length=20)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
