# Generated by Django 4.2.16 on 2026-09-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
